### ISSUE TITLE
新题目

### ISSUE THREAD

**Issue by hbcraft** [type-challenges/type-challenges#10969]
## 基本信息

```yaml
# 题目难度
difficulty: medium

# 题目标题
title: 整数

# 题目标签
tags: template-literal
```

## 题目

清完成类型`Integer<T>`,类型`T`继承于`number`,如果`T`是一个整数则返回他,否则返回`never`

## 题目模版

```ts
type Integer<T> = any
```

## 判题测试

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { ExpectFalse, NotEqual } from '@type-challenges/utils'

let x = 1
let y = 1 as const

type cases1 = [
  Expect<Equal<Integer<1>, 1>>,
  Expect<Equal<Integer<1.1>, never>>,
  Expect<Equal<Integer<1.0>, 1>>,
  Expect<Equal<Integer<typeof x>, never>>,
  Expect<Equal<Integer<typeof y>, 1>>,
]
```
