### ISSUE TITLE
PickFunction

### ISSUE THREAD

**Issue by XkSuperCool** [type-challenges/type-challenges#12898]
## 基本信息

```yaml
# 题目难度
difficulty: easy 

# 题目标题
title: PickFunction

# 题目标签
tags: function
```

## 题目

从类型 **T** 中选择出**函数**类型，构造成一个新的类型

## 题目模版

```ts
type PickFunction<T> = any
```

## 判题测试

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { ExpectFalse, NotEqual } from '@type-challenges/utils'

interface Todo {
  title: string
  description: string
  foo(): string
  bar(name: string): string
}

type cases = [
  Expect<Equal<PickFunction<Todo>, {
    foo(): string
    bar(name: string): string
  }>>
]
```
