### ISSUE TITLE
新题目

### ISSUE THREAD

**Issue by mwc** [type-challenges/type-challenges#16259]
> 请按照以下的模版填充相应的内容，一个 PR 会自动生成并保持与本 Issue 的内容同步。

> 你不需要提供详细的答案或教学，但请保证题目可解。

## 基本信息

```yaml
# 题目难度
difficulty: medium

# 题目标题
title: 将类型为字面类型（标签类型）的属性，转换为基本类型。

# 题目标签
# tags: literal type to primitive type
```ts

## 题目

<!--question-start-->

// 将类型为字面类型（标签类型）的属性，转换为基本类型。

type PersonInfo = {
  name: 'Tom',
  age: 30,
  married: false,
  addr: {
    home: '123456',
    phone: '13111111111'
  }
}

// 要求结果如下：
type PersonInfo = {
  name: string,
  age: number,
  married: boolean,
  addr: {
    home: string,
    phone: string
  }
}

<!--question-end-->

## 题目模版

以下是给予挑战者开始做题的代码模版，在大部分情况下你只需要修改类型名称使其符合你的题目与判题测试，实现的部分保持 `any` 即可。

```ts
type ToPrimitive = any
```

## 判题测试

请为你的题目提供一些判题测试，你可以使用 `@type-challenges/utils` 中提供的一些工具进行判断。

```ts
import type { Equal, Expect } from '@type-challenges/utils'

type PersonInfo = {
  name: 'Tom',
  age: 30,
  married: false,
  addr: {
    home: '123456',
    phone: '13111111111'
  },
  hobbies: ["sing","dance"]
}

type ExpectedResult = {
  name: string,
  age: number,
  married: boolean,
  addr: {
    home: string,
    phone: string
  },
  hobbies: [string, string]
}

type cases = [
  Expect<Equal<ToPrimitive<PersonInfo>, ExpectedResult>>
]
```
