### ISSUE TITLE
Add two numbers

### ISSUE THREAD

**Issue by Hacker-C** [type-challenges/type-challenges#16745]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

We all konw that `1 + 1 = 2`，but how to implement it in **TypeScript System**? Let's do it.

```yaml
difficulty: medium # medium / hard / extreme
title: Add two Numbers
#tags: # separate by comma
```

## Question

Implement an Add generic `Add<A, B>` that takes two numbers and returns sum of them.

For example:
```ts
type sum1 = Add<1, 1> // expected to be 2
type sum1 = Add<2, 2> // expected to be 4
```

## Template

```ts
type Add<A, B> = any
```

## Test Cases

```ts
import type { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Add<1, 1>, 2>>,
  Expect<Equal<Add<2, 2>, 4>>,
  Expect<Equal<Add<5, 7>, 12>>,
]
```
