### ISSUE TITLE
新题目

### ISSUE THREAD

**Issue by Big-Bear3** [type-challenges/type-challenges#17104]
## 基本信息

```yaml
# 题目难度
difficulty: hard

# 题目标题
title: 根据类的实例类型，推断其构造方法参数

# 题目标签
# tags: class, object
```

## 题目

给出一个类的实例类型T，实现`InstanceConstructorParameters<T>`，推断其构造方法参数类型。

## 题目模版

```ts
type InstanceConstructorParameters<T>= any
```

## 判题测试
```ts
class TestClass {
    constructor(code: number, name: string) {}
}

type Icp = InstanceConstructorParameters<TestClass>;  // expected to be [code: number, name: string]
```
