### ISSUE TITLE
New Challenge：Reverse tuple

### ISSUE THREAD

**Issue by cutefcc** [type-challenges/type-challenges#17964]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: easy
title: Reverse tuple
author:
  github: cutefcc
  name: cutefcc
  email: cquliuhao@gamil.com
tags: array
```

## Question

Reverse tuple, behave like：`Array.prototype.reverse()`

like：

```ts
type tech = ["html", "css", "typescript", "node"]
type num = [1, 2, 3, 4, 5]

type ReverseTech = Reverse<tech> // expected ['node', 'typescript', 'css', 'html']
type ReverseNum = Reverse<num> // expected [5, 4, 3, 2, 1]
```

## Template

```ts
type Reverse = any
```

## Test Cases 

```ts
import type { Equal, Expect } from '@type-challenges/utils'

type cases = [
    Expect<Equal<Reverse<[1, 2, 3, 4, 5]>, [5, 4, 3, 2, 1]>>,
    Expect<Equal<Reverse<[null, undefined, string, number]>, [number, string, undefined, null]>>,
    Expect<Equal<Reverse<[string, 1, number, "a", []]>, [[], "a", number, 1, string]>>,
];
```
