### ISSUE TITLE
新题目: 组合键类型 Combination key type

### ISSUE THREAD

**Issue by Nauxscript** [type-challenges/type-challenges#21106]
> 请按照以下的模版填充相应的内容，一个 PR 会自动生成并保持与本 Issue 的内容同步。

> 你不需要提供详细的答案或教学，但请保证题目可解。

## 基本信息

```yaml
# 题目难度
difficulty: medium

# 题目标题
title: 组合键类型 Combination key type

# 题目标签
# tags: array, infer
```

## 题目

1. 把多个修饰键两两组合，但不可以出现相同的修饰键组合。
2. 提供的 `ModifierKeys` 中，前面的值比后面的值高，即 `cmd ctrl` 是可以的，但 `ctrl cmd` 是不允许的。 

## 题目模版
```ts
type ModifierKeys = ['cmd', 'ctrl', 'opt', 'fn']

// 实现 Combs
type Combs = any

```

## 判题测试

请为你的题目提供一些判题测试，你可以使用 `@type-challenges/utils` 中提供的一些工具进行判断。

```ts
import type { Equal, Expect } from '@type-challenges/utils'

type CaseTypeOne = "cmd ctrl" | "cmd opt" | "cmd fn" | "ctrl opt" | "ctrl fn" | "opt fn"

type cases = [
  Expect<Equal<Combs, CaseTypeOne>>
]
```
