### ISSUE TITLE
get keys and  sub keys of object example

### ISSUE THREAD

**Issue by wassimnassour** [type-challenges/type-challenges#21497]
## Info

Basic info of your challenge questions,

```yaml
difficulty: # medium 
title: get keys and  sub keys of object example {fullname:{name:string }}  `fullname.name`
# tags:  Objects 
```

## Question

i was working on form and i found this challange  have this objects 

```ts
{
  date {
    from: string,
      to: string
  }
}
```

get keys and  sub keys of object   exmple of results  `date` | `date.from` | `date.to`

## Template

```ts
type NestedKeys = any
```

solution :

```ts

type DotPrefix<T extends string> = T extends '' ? '' : `.${T}`;

export type DotNestedKeys<T> = (
  T extends object
    ? {
        [K in Exclude<keyof T, symbol>]: `${K}${DotPrefix<
          DotNestedKeys<T[K]>
        >}`;
      }[Exclude<keyof T, symbol>]
    : ''
) extends infer D
  ? Extract<D, string>
  : never;

```
