### ISSUE TITLE
mzy

### ISSUE THREAD

**Issue by Mzyyyyy** [type-challenges/type-challenges#2382]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: easy # medium / hard / extreme
title: Your Question Name
#tags: union, array # separate by comma
```

## Question

Describe your question and give some examples. Markdown is supported here. 

## Template

This is the template for challengers to start the coding. Basically, you just need to change the name of your generic/function and leave to implementation `any`.

```ts
type YourType = any
```

## Test Cases

Provide some test cases for your challenge, you can use some utils from `@type-challenges/utils` for asserting.  

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<true, true>>
]
```
