### ISSUE TITLE
New Challenge : trace

### ISSUE THREAD

**Issue by csharpython** [type-challenges/type-challenges#35191]
> テンプレートに従って内容を記入してください。PRは自動生成され、常にあなたの変更が反映されます。
>
> 詳細な解答/ガイドは必要ありませんが、課題が解決可能であることを確認してください。

## 基本情報

```yaml
# 難易度
difficulty: medium # easy / hard / extreme

# タイトル
title: Trace

# タグ
# tags: array,math # separate by comma
```

## 質問

行列において、トレースは主対角成分の総和です。
それを型システムを使って求めたいです。
しかし、型で数を足すのは難しいため、代わりに主対角成分のユニオン型を求めてください。

例：
```ts
type Arr = [
  [1,2],
  [3,4]
]
type Test = Trace<Arr> // expected to be 1 | 4
```

## テンプレート

課題の挑戦者がコーディングを始める際のテンプレートです。基本的には質問とテストに合わせて型の名前を変更して、実装は `any` とするだけです。

```ts
type Trace<T extends any[][]> = any
```

## テストケース

あなたの課題のテストケースです。`@type-challenges/utils`が提供するいくつかのアサーションを使うことが出来ます。

```ts
import type { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Trace<[[1,2],[3,4]]>, 1 | 4>>,
  Expect<Equal<Trace<[[0,1,1],[2,0,2],[3,3,0]]>, 0>>,
  Expect<Equal<Trace<[['a','b',''],['c','',''],['d','e','f']]>, 'a' | '' | 'f'>>
]
```
