### ISSUE TITLE
新题目

### ISSUE THREAD

**Issue by wind-liang** [type-challenges/type-challenges#4182]
## 基本信息

```yaml
# 题目难度
difficulty: medium

# 题目标题
title: Fibonacci Sequence

# 题目标签
#tags: recursion, array
```

## 题目

Implement a generic Fibonacci\<T\> takes an number T and returns it's corresponding [Fibonacci number](https://en.wikipedia.org/wiki/Fibonacci_number).

The sequence starts:
1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ...

For example
```js
type Result1 = Fibonacci<3> // 2
type Result2 = Fibonacci<8> // 21
```

## 题目模版

```ts
type Fibonacci<T extends number> = any
```

## 判题测试

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Fibonacci<3>, 2>>,
  Expect<Equal<Fibonacci<8>, 21>>,
]
```
