### ISSUE TITLE
Union to Intersection

### ISSUE THREAD

**Issue by zheeeng** [type-challenges/type-challenges#55]
## Info

```yaml
difficulty: hard
title: Union to Intersection
tags: utils, infer
```

## Question

Implement the advanced util type `UnionToIntersection<U>`

For example

```ts
type I = Union2Intersection<'foo' | 42 | true> // expected to be 'foo' & 42 & true
```

## Template

```ts
type UnionToIntersection<U> = any
```

## Test Cases

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
    Expect<Equal<UnionToIntersection<'foo' | 42 | true>, 'foo' & 42 & true>>,
    Expect<Equal<UnionToIntersection<(() => 'foo') | ((i: 42) => true)>, (() => 'foo') & ((i: 42) => true)>>,
]
```
