### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by daixiongsheng** [type-challenges/type-challenges#8025]
## 基本信息

```yaml
# 题目难度
difficulty: easy # medium / hard / extreme

# 题目标题
title: Add

# 题目标签
#tags: tuple # separate by comma
```

## 题目

  
  ```ts

  type R1 = Add<1, 2> // expected to be 3
  type R2 = Add<100, 100> // expected to be 200
  ```

## 题目模版

```ts
type Add = any
```

## 判题测试

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Add<1, 2>, 3>>
  Expect<Equal<Add<100, 100>, 200>>
]
```
