### ISSUE TITLE
Divide

### ISSUE THREAD

**Issue by daixiongsheng** [type-challenges/type-challenges#8027]
## 基本信息

```yaml
# 题目难度
difficulty: medium # medium / hard / extreme

# 题目标题
title: Divide

# 题目标签
#tags: tuple # separate by comma
```

## 题目

```TS
type A = Divide<10, 3> // 3
type B = Divide<10, 2> // 5
type C = Divide<10, 0> // never
```

## 题目模版

```ts
type Divide = any
```

## 判题测试

请为你的题目提供一些判题测试，你可以使用 `@type-challenges/utils` 中提供的一些工具进行判断。

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Divide<10, 3>, 3>>,
  Expect<Equal<Divide<10, 2>, 5>>,
  Expect<Equal<Divide<10, 0>, never>>
]
```
