### ISSUE TITLE
Multiply

### ISSUE THREAD

**Issue by daixiongsheng** [type-challenges/type-challenges#8029]
> 请按照以下的模版填充相应的内容，一个 PR 会自动生成并保持与本 Issue 的内容同步。

> 你不需要提供详细的答案或教学，但请保证题目可解。

## 基本信息

```yaml
# 题目难度
difficulty: medium # medium / hard / extreme

# 题目标题
title: Multiply

# 题目标签
#tags: tuple # separate by comma
```

## 题目

```TS
type A = Multiply<3, 3> // 9
type B = Multiply<10, 2> // 20
type C = Multiply<10, 0> // 0
```

## 题目模版

```ts
type Multiply = any
```

## 判题测试

请为你的题目提供一些判题测试，你可以使用 `@type-challenges/utils` 中提供的一些工具进行判断。

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
   Expect<Equal<Multiply<3, 3>, 9>>,
   Expect<Equal<Multiply<10, 0>, 0>>,
   Expect<Equal<Multiply<0, 10>, 0>>
]
```
