### ISSUE TITLE
Pow

### ISSUE THREAD

**Issue by daixiongsheng** [type-challenges/type-challenges#8031]
> 请按照以下的模版填充相应的内容，一个 PR 会自动生成并保持与本 Issue 的内容同步。

> 你不需要提供详细的答案或教学，但请保证题目可解。

## 基本信息

```yaml
# 题目难度
difficulty: medium # medium / hard / extreme

# 题目标题
title: Pow

# 题目标签
#tags: tuple # separate by comma
```

## 题目

```ts
type A = Pow<3, 3> // 27
type B = Pow<10, 2> // 100
type C = Pow<10, 0> // 1
type D = Pow<10, 1> // 10
```

## 题目模版

```ts
type Pow = any
```

## 判题测试

```ts
import { Equal, Expect, ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<Pow<3, 3>, 27>>,
  Expect<Equal<Pow<10, 0>, 1>>,
  Expect<Equal<Pow<2, 10>, 1024>>
]
```
