### ISSUE TITLE
Optional Keys

### ISSUE THREAD

**Issue by yi-tuan** [type-challenges/type-challenges#90]
## Info

```yaml
difficulty: hard
title: Optional Keys
tags: utils
related: 89, 5
```

## Question

Implement the advanced util type `OptionalKeys<T>`, which picks all the optional keys into a union.

## Template

```ts
type OptionalKeys<T> = any
```

## Test Cases

```ts
import { Equal, Expect } from '@type-challenges/utils'

type cases = [
    Expect<Equal<OptionalKeys<{ a: number, b?: string }>, "b">>,
    Expect<Equal<OptionalKeys<{ a: undefined, b?: undefined }>, "b">>,
    Expect<Equal<OptionalKeys<{ a: undefined, b?: undefined, c?: string, d?: null }>, "b" | "c" | "d">>
    Expect<Equal<OptionalKeys<{}>, never>>
]
```
