### ISSUE TITLE
新题目 CheckRepeatedChars

### ISSUE THREAD

**Issue by RThong** [type-challenges/type-challenges#9142]
> 请按照以下的模版填充相应的内容，一个 PR 会自动生成并保持与本 Issue 的内容同步。

> 你不需要提供详细的答案或教学，但请保证题目可解。

## 基本信息

```yaml
# 题目难度
difficulty: medium 

# 题目标题
title: CheckRepeatedChars

# 题目标签
tags: union, string
```

## 题目

判断一个string类型中是否有相同的字符
```ts
type CheckRepeatedChars<'abc'>   // false
type CheckRepeatedChars<'aba'>   // true
```

## 题目模版

以下是给予挑战者开始做题的代码模版，在大部分情况下你只需要修改类型名称使其符合你的题目与判题测试，实现的部分保持 `any` 即可。

```ts
type CheckRepeatedChars<T extends string> = any
```

## 判题测试

请为你的题目提供一些判题测试，你可以使用 `@type-challenges/utils` 中提供的一些工具进行判断。

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<CheckRepeatedChars<'abc'>, false>>,
  Expect<Equal<CheckRepeatedChars<'abb'>, true>>,
  Expect<Equal<CheckRepeatedChars<'cbc'>, true>>,
  Expect<Equal<CheckRepeatedChars<''>, false>>
]
```
