### ISSUE TITLE
找出目标数组中只出现过一次的元素

### ISSUE THREAD

**Issue by brenner8023** [type-challenges/type-challenges#9898]
> 请按照以下的模版填充相应的内容，一个 PR 会自动生成并保持与本 Issue 的内容同步。

> 你不需要提供详细的答案或教学，但请保证题目可解。

## 基本信息

```yaml
# 题目难度
difficulty: medium

# 题目标题
title: 找出目标数组中只出现过一次的元素

# 题目标签
# tags: array
```

## 题目

找出目标数组中只出现过一次的元素。例如：输入[1,2,2,3,3,4,5,6,6,6]，输出[1,4,5]

## 题目模版

以下是给予挑战者开始做题的代码模版，在大部分情况下你只需要修改类型名称使其符合你的题目与判题测试，实现的部分保持 `any` 即可。

```ts
type FindEles<T extends any[]> = any
```

## 判题测试

请为你的题目提供一些判题测试，你可以使用 `@type-challenges/utils` 中提供的一些工具进行判断。

```ts
import type { Equal, Expect } from '@type-challenges/utils'
import { ExpectFalse, NotEqual } from '@type-challenges/utils'

type cases = [
  Expect<Equal<FindEles<[1,2,2,3,3,4,5,6,6,6]>, [1,4,5]>>,
  Expect<Equal<FindEles<[2,2,3,3,6,6,6]>, []>>,
  Expect<Equal<FindEles<[1,2,3]>, [1,2,3]>>,
]
```
